/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package compuWork.CapaPresentacion;

import compuWork.LogicaNegocio.Departamento;
import compuWork.LogicaNegocio.GestionEmpresa;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Brislleily S.Carmona
 */
public class GestionDepartamento extends javax.swing.JDialog {
    private GestionEmpresa gestion;
    private Modelo ventana;
    private ArrayList<Departamento> departamentos;
  
    public GestionDepartamento(java.awt.Frame parent, boolean modal, GestionEmpresa gestion, Modelo ventana) {
        super(parent, modal);
        initComponents();
     
        this.setLocationRelativeTo(null);
        try {
           this.setIconImage(new ImageIcon(getClass().getResource("/compuWork/Imagenes/Empresa.png")).getImage()); 
        } catch (Exception e) {
            System.out.println("Error al cargar imagen");
        }
        this.gestion=gestion;
        this.ventana=ventana;
        this.departamentos=gestion.obtenerDepartamento();
        this.llenarTabla();
        
    }
        public void llenarTabla(){
        DefaultTableModel tablaModelo= new DefaultTableModel(new String[] {"nombre","id","Descripcion"},departamentos.size());
        this.tblDepto.setModel(tablaModelo);
        TableModel datosModelo=tblDepto.getModel();
        for (int i = 0; i < departamentos.size(); i++) {
            Departamento d=this.departamentos.get(i);
            datosModelo.setValueAt(d.getNombreDepto(),i,0);
            datosModelo.setValueAt(d.getIdDepto(),i,1);  
            datosModelo.setValueAt(d.getDescripcion(),i,2);

        }
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDepto = new javax.swing.JTable();
        btnCrearDepto = new javax.swing.JButton();
        btnActualizarDepto = new javax.swing.JButton();
        btnEliminarDepto = new javax.swing.JButton();
        btnVolverDepto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(128, 0, 32));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("SimSun", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GESTION DEPARTAMENTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(30, 30, 30))
        );

        jPanel2.setBackground(new java.awt.Color(247, 234, 218));

        tblDepto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDepto.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblDepto);
        if (tblDepto.getColumnModel().getColumnCount() > 0) {
            tblDepto.getColumnModel().getColumn(0).setResizable(false);
            tblDepto.getColumnModel().getColumn(1).setResizable(false);
            tblDepto.getColumnModel().getColumn(2).setResizable(false);
        }

        btnCrearDepto.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        btnCrearDepto.setText("Crear");
        btnCrearDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearDeptoActionPerformed(evt);
            }
        });

        btnActualizarDepto.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        btnActualizarDepto.setText("Actualizar");
        btnActualizarDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarDeptoActionPerformed(evt);
            }
        });

        btnEliminarDepto.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        btnEliminarDepto.setText("Eliminar");
        btnEliminarDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDeptoActionPerformed(evt);
            }
        });

        btnVolverDepto.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        btnVolverDepto.setText("Volver");
        btnVolverDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverDeptoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCrearDepto)
                        .addGap(71, 71, 71)
                        .addComponent(btnActualizarDepto)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(btnVolverDepto))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btnEliminarDepto)))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolverDepto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrearDepto)
                            .addComponent(btnActualizarDepto)
                            .addComponent(btnEliminarDepto))
                        .addContainerGap(39, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearDeptoActionPerformed
        CrearDepartamento crear=new CrearDepartamento(this.ventana, true,gestion, this.ventana);
        crear.setVisible(true);
    }//GEN-LAST:event_btnCrearDeptoActionPerformed

    private void btnEliminarDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDeptoActionPerformed
        int fila=this.tblDepto.getSelectedRow();
        if(fila>=0){
            Departamento d=this.departamentos.get(fila);
          int opc=JOptionPane.showConfirmDialog(this,"Deseas eliminar el Departamento: "+d.getNombreDepto());
            if (opc==0) {
            this.gestion.eliminarDepartamento(d.getIdDepto());
            this.departamentos=this.gestion.obtenerDepartamento();
            this.llenarTabla();
            }
        }else{
            JOptionPane.showMessageDialog(this,"Debe seleccionar un departamento a eliminar");
        }
    }//GEN-LAST:event_btnEliminarDeptoActionPerformed

    private void btnVolverDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverDeptoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverDeptoActionPerformed

    private void btnActualizarDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarDeptoActionPerformed
        int fila=this.tblDepto.getSelectedRow();
        if (fila>=0) {
            Departamento d= this.departamentos.get(fila);
            ModificarDepartamento modificar =new ModificarDepartamento(this.ventana,true, gestion, this,d);
            modificar.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this,"Debe seleccionar un producto a actualizar");
        }
    }//GEN-LAST:event_btnActualizarDeptoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarDepto;
    private javax.swing.JButton btnCrearDepto;
    private javax.swing.JButton btnEliminarDepto;
    private javax.swing.JButton btnVolverDepto;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDepto;
    // End of variables declaration//GEN-END:variables
}
